### ISSUE TITLE
建议取消time.sleep()

### ISSUE THREAD

**Issue by EricDing618** [Meltide/mpga-pyos#9]
在time.sleep()的时候，实际程序并没有执行什么大量东西，这反而是浪费时间、堵塞线程，因此建议不要用time.sleep，这只是一个表面的东西，没有任何意义

**Comment by Meltide** [comment]
只是为了仿真搞的，没有别的意思

**Comment by EricDing618** [comment]
> 只是为了仿真搞的，没有别的意思

好吧
